name: CI/CD Tienda Backend Despacho

on:
  push:
    branches: [ "deploy" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, Tag, and Push Image to ECR
      env:
        REGISTRY: ${{ secrets.ECR_REGISTRY }}
        REPOSITORY: ${{ secrets.ECR_REPO_URL_BACKDESPACHO }}
        IMAGE_TAG: v1
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f ./Springboot-API-REST-DESPACHO/dockerfile ./Springboot-API-REST-DESPACHO
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    # ========================================================
    # DESPLIEGUE SEGURO EN SUBRED PRIVADA USANDO AWS CLI NATIVO (SSM)
    # ========================================================
    - name: Deploy to Private EC2 via AWS CLI SSM
      run: |
        aws ssm send-command \
          --instance-ids "${{ secrets.EC2_HOST }}" \
          --document-name "AWS-RunShellScript" \
          --comment "Desplegando actualizacion de Backend Despacho" \
          --parameters 'commands=[
            "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}",
            "mkdir -p ~/app-despacho && cd ~/app-despacho",
            "docker pull ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_URL_BACKDESPACHO }}:v1",
            "docker stop tienda-backend-despacho || true",
            "docker rm tienda-backend-despacho || true",
            "docker run -d -p 8081:8081 --name tienda-backend-despacho ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_URL_BACKDESPACHO }}:v1"
          ]' \
          --region ${{ secrets.AWS_REGION }}